---
# =====================================
# 生产环境专用配置
# =====================================
deploy_environment: production
admin_email: "owen@owenyoung.com"
app1_domain: demo-0907.owenyoung.com

# SSH 密钥（生产环境）
deploy_ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINAPcRy9wGjP47bHpv2RcNO3yw3udCcTlgWs22KLcpUW main@example.com"


# 基础必装包
common_packages:
  - curl
  - wget
  - vim

# 只覆盖必要的配置，其余使用默认值
# =====================================
# 用户配置（仅必要项）
# =====================================
users_user_list:
  - name: deploy
    groups: [sudo, docker]
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    authorized_keys: "{{ deploy_ssh_keys }}"

# =====================================
# SSH 配置（仅关键安全项）
# =====================================
sshd:
  PermitRootLogin: "no"
  PasswordAuthentication: "no"

# =====================================
# 防火墙（geerlingguy.firewall 配置）
# =====================================
# 禁用冲突的防火墙服务
firewall_disable_firewalld: true
firewall_disable_ufw: true

# 允许的端口配置
firewall_allowed_tcp_ports:
  - "22"    # SSH
  - "80"    # HTTP
  - "443"   # HTTPS

firewall_allowed_udp_ports:
  - "443"   # QUIC/HTTP3

# 防火墙服务状态
firewall_state: started
firewall_enabled_at_boot: true

# =====================================
# Docker
# =====================================
docker_users:
  - deploy

# =====================================
# Caddy 配置（生产环境）
# =====================================
caddy_email: "{{ admin_email }}"
caddy_sites:
  - domain: "{{ app1_domain }}"
    config: |
      root * /app/public
      file_server
      encode gzip
      
      handle /api/* {
        reverse_proxy app:3000
      }

caddy_config: |
  {
    email {{ caddy_email }}
  }
  
  {% for site in caddy_sites %}
  {{ site.domain }} {
    {{ site.config | indent(4) }}
  }
  {% endfor %}

# =====================================
# 应用配置
# =====================================
app_name: myapp
app_port: 3000
app_directory: js-apps/bun-demo6
app_git_repo: "https://github.com/theowenyoung/studio"
app_git_branch: main
