- name: Update package cache
  ansible.builtin.package:
    update_cache: true
  tags: packages

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  tags: packages

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"
  notify: restart rsyslog
  tags: timezone

- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user_name }}"
    shell: "{{ admin_user_shell }}"
    groups: "{{ admin_user_groups }}"
    append: true
  tags: users

- name: Set up admin user SSH key from GitHub
  ansible.posix.authorized_key:
    user: "{{ admin_user_name }}"
    key: "https://github.com/{{ github_username }}.keys"
    state: present
  when:
    - admin_user_name is defined
    - github_username is defined
  tags: ssh
- name: Configure sudoers for admin user (NOPASSWD) - after hardening
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ admin_user_name }}
    line: "{{ admin_user_name }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    mode: '0440'
    validate: 'visudo -cf %s'
  when:
    - admin_user_name is defined
    - admin_user_sudo_nopasswd | default(false)
  tags: [sudo]

- name: Apply OS hardening
  ansible.builtin.include_role:
    name: devsec.hardening.os_hardening
  tags: [hardening, security]

- name: Apply SSH hardening  
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening
  tags: [hardening, security]
- name: Install and configure Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_users:
      - "{{ admin_user_name }}"  # 用前面创建的管理员用户
  tags: [docker, containers]
