# =====================================
# PostgreSQL 生产环境配置
# =====================================
services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    
    environment:
      # 核心配置
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
      # 性能配置
      POSTGRES_SHARED_PRELOAD_LIBRARIES: 'pg_stat_statements'
      
      # 本地化
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    
    # 生产环境不暴露端口（仅内部访问）
    expose:
      - "5432"
    
    volumes:
      # 生产数据目录
      - /data/postgres/data:/var/lib/postgresql/data
      
      # 初始化脚本
      - ./init:/docker-entrypoint-initdb.d:ro
      
      # 生产备份目录
      - /data/backups/postgres:/backups
    
    networks:
      - shared_network
    
    # 环境变量文件（仅敏感信息）
    env_file:
      - .env
    
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    # 生产环境性能配置（高性能配置）
    command: >
      postgres
      -c shared_buffers=1GB
      -c effective_cache_size=4GB
      -c maintenance_work_mem=256MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=32MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=8MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_connections=200
      -c log_min_duration_statement=1000
      -c log_checkpoints=on
      -c log_connections=on
      -c log_disconnections=on
      -c shared_preload_libraries=pg_stat_statements
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
      -c log_rotation_age=1d
      -c log_rotation_size=1GB
      -c log_truncate_on_rotation=on
    
    # 日志配置
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  shared_network:
    external: true
