---
# =====================================
# PostgreSQL 基础设施部署
# 使用统一部署脚本
# =====================================
- name: Deploy PostgreSQL Infrastructure
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
    - name: 部署 PostgreSQL 服务
      script: "{{ playbook_dir }}/../../infra-apps/postgres/deploy.sh"
      environment:
        ENV_MODE: aws
        AWS_REGION: "{{ aws_region | default('us-west-2') }}"
        DEPLOY_USER: "{{ deploy_user | default('deploy') }}"
      register: postgres_deploy_result

    - name: 显示部署结果
      debug:
        var: postgres_deploy_result.stdout_lines
