---
# =====================================
# 通用基础设施服务部署
# 使用统一部署脚本
# =====================================
- name: Deploy Infrastructure Service
  hosts: all
  gather_facts: yes
  become: yes
  
  vars:
    service_name: "{{ service }}"  # 必须参数：服务名 (postgres, redis, caddy, database-tasks, app)
    
  tasks:
    - name: 验证服务名称
      fail:
        msg: "请指定服务名称: --extra-vars service=postgres|redis|caddy|database-tasks|app"
      when: service_name is not defined
      
    - name: 验证服务部署脚本存在
      local_action:
        module: stat
        path: "{{ playbook_dir }}/../../infra-apps/{{ service_name }}/deploy.sh"
      register: deploy_script_stat
      become: false
      
    - name: 服务部署脚本不存在时失败
      fail:
        msg: "服务 {{ service_name }} 的部署脚本不存在: infra-apps/{{ service_name }}/deploy.sh"
      when: not deploy_script_stat.stat.exists

    - name: 部署基础设施服务
      script: "{{ playbook_dir }}/../../infra-apps/{{ service_name }}/deploy.sh"
      environment:
        ENV_MODE: aws
        AWS_REGION: "{{ aws_region | default('us-west-2') }}"
        DEPLOY_USER: "{{ deploy_user | default('deploy') }}"
      register: service_deploy_result

    - name: 显示部署结果
      debug:
        var: service_deploy_result.stdout_lines