---
# =====================================
# Database Tasks 基础设施部署
# 使用统一部署脚本
# =====================================
- name: Deploy Database Tasks Infrastructure
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
    - name: 设置 Database Tasks 环境
      script: "{{ playbook_dir }}/../../infra-apps/database-tasks/deploy.sh setup"
      environment:
        ENV_MODE: aws
        AWS_REGION: "{{ aws_region | default('us-west-2') }}"
        DEPLOY_USER: "{{ deploy_user | default('deploy') }}"
      register: db_tasks_setup_result
    
    - name: 显示设置结果
      debug:
        var: db_tasks_setup_result.stdout_lines

    # 可选：执行指定的数据库任务
    - name: 执行数据库任务
      script: "{{ playbook_dir }}/../../infra-apps/database-tasks/deploy.sh run {{ task_name }}"
      environment:
        ENV_MODE: aws
        AWS_REGION: "{{ aws_region | default('us-west-2') }}"
        DEPLOY_USER: "{{ deploy_user | default('deploy') }}"
      register: db_task_result
      when: task_name is defined and task_name != ""
      
    - name: 显示任务执行结果
      debug:
        var: db_task_result.stdout_lines
      when: task_name is defined and task_name != "" and db_task_result is defined