---
# =====================================
# 独立服务批量部署
# 依次调用各个服务的部署 playbook
# =====================================
- name: Deploy All Standalone Services
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: 显示批量部署计划
      debug:
        msg:
          - "=== 独立服务批量部署 ==="
          - "环境: {{ deploy_environment | default('production') }}"
          - "数据目录: /data/"
          - "共享网络: shared_network"
          - ""
          - "部署顺序:"
          - "1. PostgreSQL"
          - "2. Redis" 
          - "3. Caddy"
          - "========================="
      tags: [info]

    # 确保基础设施已准备好
    - name: 检查共享网络是否存在
      command: docker network inspect shared_network
      register: network_check
      changed_when: false
      failed_when: false
      become_user: "{{ deploy_user | default('deploy') }}"
      tags: [verify]

    - name: 提示运行基础设施准备
      fail:
        msg: |
          共享网络不存在，请先运行基础设施准备:
          ansible-playbook ansible/playbooks/infra.yml
      when: network_check.rc != 0
      tags: [verify]

    - name: 批量部署说明
      debug:
        msg:
          - "📋 批量部署将按以下顺序执行:"
          - "   ansible-playbook ansible/playbooks/deploy-postgres-infra.yml"
          - "   ansible-playbook ansible/playbooks/deploy-redis-infra.yml"  
          - "   ansible-playbook ansible/playbooks/deploy-caddy-infra.yml"
          - ""
          - "💡 也可以单独执行:"
          - "   mise run postgres"
          - "   mise run redis"
          - "   mise run caddy"
          - ""
          - "⚠️  请手动执行上述命令，或使用对应的 mise 任务"
      tags: [info]

# =====================================
# 导入各个服务的部署 playbook
# =====================================
- import_playbook: deploy-postgres-infra.yml
- import_playbook: deploy-redis-infra.yml  
- import_playbook: deploy-caddy-infra.yml