---
- name: Deploy Caddy Reverse Proxy
  hosts: all
  gather_facts: yes
  
  pre_tasks:
    - name: Update package cache
      package:
        update_cache: yes
      tags: [caddy, setup]

  roles:
    # Caddy反向代理服务
    - role: maxhoesel.caddy.caddy_server
      tags: [caddy, proxy]
  
  tasks:
    - name: Ensure Caddy service is running
      systemd:
        name: caddy
        state: started
        enabled: yes
      tags: [caddy, proxy]

    - name: Wait for Caddy to be ready
      uri:
        url: "http://localhost:2019/config/"
        method: GET
        status_code: [200, 404]  # 404 is ok if no config loaded yet
      register: caddy_ready
      retries: 10
      delay: 3
      until: caddy_ready.status in [200, 404]
      tags: [caddy, health-check]

    - name: Test Caddy admin API
      uri:
        url: "http://localhost:2019/config/"
        method: GET
      register: caddy_config
      tags: [caddy, test]

    - name: Create Caddyfile from template
      template:
        src: Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        owner: caddy
        group: caddy
        mode: '0644'
      notify: reload caddy
      tags: [caddy, config]

    - name: Reload Caddy configuration
      systemd:
        name: caddy
        state: reloaded
      tags: [caddy, config]

    - name: Display Caddy service info
      debug:
        msg:
          - "Caddy: 反向代理服务运行正常 ✓"
          - "管理API: http://localhost:2019"
          - "HTTP端口: 80"
          - "HTTPS端口: 443"
          - "配置文件: /etc/caddy/Caddyfile"
          - "管理邮箱: {{ caddy_email | default('admin@example.com') }}"
      tags: [caddy, info]

  handlers:
    - name: reload caddy
      systemd:
        name: caddy
        state: reloaded
