---
- name: Bootstrap Infrastructure
  hosts: all
  gather_facts: yes
  
  pre_tasks:
    - name: Include wait for connection
      include_tasks: ../tasks/wait-for-connection.yml
      tags: [always]
  
- import_playbook: bootstrap.yml
- import_playbook: security.yml
