---
- name: Generate .env file
  template:
    src: env.j2
    dest: "{{ app_directory }}/.env"
    owner: deploy
    group: deploy
    mode: '0600'
  tags: [docker, app-config]

- name: Create uploads directory
  file:
    path: "{{ app_directory }}/uploads"
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'
  tags: [docker, app-setup]

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ app_name }}:{{ app_git_branch | default('latest') }}"
    build:
      path: "{{ app_directory }}"
      dockerfile: Dockerfile
    source: build
    force_source: yes
  become_user: deploy
  tags: [docker-build]

- name: Create systemd service file
  template:
    src: webapp.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart webapp service
  tags: [docker, systemd]

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  tags: [docker, systemd]

- name: Enable and start webapp service
  systemd:
    name: "{{ app_name }}.service"
    enabled: yes
    state: started
  tags: [docker, systemd]
