---
# 原生数据库服务管理任务

- name: Ensure PostgreSQL service is running
  systemd:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes
  tags: [database, postgresql]

- name: Ensure Redis service is running
  systemd:
    name: redis
    state: started
    enabled: yes
  tags: [database, redis]

- name: Wait for PostgreSQL to be ready
  postgresql_ping:
    db: "{{ postgres_db }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    login_host: "localhost"
  register: postgres_ready
  retries: 10
  delay: 3
  until: postgres_ready is success
  tags: [database, health-check]

- name: Wait for Redis to be ready  
  redis:
    command: ping
    login_host: localhost
    login_port: "{{ redis_port }}"
    login_password: "{{ redis_password | default(omit) }}"
  register: redis_ready
  retries: 10
  delay: 3
  until: redis_ready is success
  tags: [database, health-check]

- name: Display database connection info
  debug:
    msg:
      - "PostgreSQL: 数据库服务运行正常 ✓"
      - "Redis: 缓存服务运行正常 ✓"
      - "数据库连接: postgresql://{{ postgres_user }}:***@localhost:5432/{{ postgres_db }}"
      - "Redis连接: redis://localhost:{{ redis_port }}"
  tags: [database, info]

- name: Create database backup directory
  file:
    path: "{{ app_directory }}/backups"
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'
  tags: [database, backup]

- name: Create PostgreSQL backup script
  template:
    src: pg_backup.sh.j2
    dest: "{{ app_directory }}/backups/pg_backup.sh"
    owner: deploy
    group: deploy
    mode: '0755'
  tags: [database, backup]
