apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: studio
